[project]
name = "sacrypt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[project.scripts]
analysis = "sacrypt.__main__:main"