[project]
name = "sacrypt"
version = "0.1.0"
description = "Cryptanalysis examples for SAC"
readme = "README.md"
requires-python = ">=3.13"

[dependency-groups]
dev = ["pytest>=8.3.5"]

[project.scripts]
sacrypt = "sacrypt:main"